server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person_from_crud_app?ssl-mode=REQUIRED&serverTimezone=Europe/Moscow
    username: Admin
    password: Tamikwqwqw1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true